name: Build and Release

on:
  push:
    tags:
      - 'v1.0'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --name PhotoWatermark watermark_gui.py
      - name: Package artifact
        shell: bash
        run: |
          cd dist
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a PhotoWatermark-Windows.zip PhotoWatermark.exe
          else
            if [ -d "PhotoWatermark.app" ]; then
              zip -r PhotoWatermark-macOS.zip PhotoWatermark.app
            else
              zip PhotoWatermark-macOS.zip PhotoWatermark
            fi
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifact
          path: |
            dist/PhotoWatermark-*.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Gather files
        run: |
          ls -R artifacts
          mkdir upload
          find artifacts -name "PhotoWatermark-*.zip" -exec cp {} upload/ \;
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: upload/PhotoWatermark-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
